CREATE TABLE IF NOT EXISTS public.writers_posts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    writer_id bigint NOT NULL,
    post_id bigint NOT NULL,
    CONSTRAINT writers_posts_pkey PRIMARY KEY (id),
    CONSTRAINT post_id FOREIGN KEY (post_id)
        REFERENCES public.posts (post_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT writer_id FOREIGN KEY (writer_id)
        REFERENCES public.writers (writer_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

    TABLESPACE pg_default;

--ALTER TABLE IF EXISTS public.writers_posts
 --   OWNER to postgres;