-- DROP TABLE IF EXISTS public.labels;

CREATE TABLE IF NOT EXISTS public.labels
(
    label_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT label_pkey PRIMARY KEY (label_id),
    CONSTRAINT labels_name_key UNIQUE (name)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.labels
    OWNER to postgres;

